<?php defined('iPHP') OR exit('What are you doing?');?>
{
    "id": "{app}",
    "caption": "{name}",
    "icon": "pencil-square-o",
    "children": [{
        "caption": "{name}系统配置",
        "href": "{app}&do=config",
        "icon": "cog"
    },{
        "caption": "-"
    }, {
        "caption": "栏目管理",
        "href": "{app}_category",
        "icon": "list-alt"
    }, {
        "caption": "添加栏目",
        "href": "{app}_category&do=add",
        "icon": "edit"
    }, {
        "caption": "-"
    }, {
        "caption": "添加{name}",
        "href": "{app}&do=add",
        "icon": "edit"
    }, {
        "caption": "{name}管理",
        "href": "{app}&do=manage",
        "icon": "list-alt"
    }, {
        "caption": "草稿箱",
        "href": "{app}&do=inbox",
        "icon": "inbox"
    }, {
        "caption": "回收站",
        "href": "{app}&do=trash",
        "icon": "trash-o"
    }, {
        "caption": "-"
    }, {
        "caption": "用户{name}管理",
        "href": "{app}&do=user",
        "icon": "check-circle"
    }, {
        "caption": "审核用户{name}",
        "href": "{app}&do=examine",
        "icon": "minus-circle"
    }, {
        "caption": "淘汰的{name}",
        "href": "{app}&do=off",
        "icon": "times-circle"
    }, {
        "caption": "-"
    }, {
        "caption": "{name}评论管理",
        "href": "comment&appname={app}&appid={appid}",
        "icon": "comments"
    }]
}
