<?php defined('iPHP') OR exit('What are you doing?');?>
[{
    "id": "system",
    "sort": "9999999",
    "caption": "系统",
    "icon": "cog",
    "children": [{
            "id": "config",
            "caption": "系统设置",
            "href": "config",
            "icon": "cog",
            "children": [{
                "caption": "网站设置",
                "href": "config&tab=base",
                "icon": "cog"
            }, {
                "caption": "模板设置",
                "href": "config&tab=tpl",
                "icon": "cog"
            }, {
                "caption": "URL设置",
                "href": "config&tab=url",
                "icon": "cog"
            }, {
                "caption": "缓存设置",
                "href": "config&tab=cache",
                "icon": "cog"
            }, {
                "caption": "附件设置",
                "href": "config&tab=file",
                "icon": "cog"
            }, {
                "caption": "缩略图设置",
                "href": "config&tab=thumb",
                "icon": "cog"
            }, {
                "caption": "水印设置",
                "href": "config&tab=watermark",
                "icon": "cog"
            }, {
                "caption": "其它设置",
                "href": "config&tab=other",
                "icon": "cog"
            }, {
                "caption": "更新设置",
                "href": "config&tab=patch",
                "icon": "cog"
            }, {
                "caption": "高级设置",
                "href": "config&tab=grade",
                "icon": "cog"
            }]
        }, {
            "-": "-"
        }, {
            "id": "apps",
            "caption": "应用管理",
            "icon": "code",
            "children": [{
                "caption": "应用管理",
                "href": "apps",
                "icon": "code"
            }, {
                "caption": "添加应用",
                "href": "apps&do=add",
                "icon": "pencil-square-o"
            }, {
                "-": "-"
            }, {
                "caption": "表单管理",
                "href": "form",
                "icon": "building"
            },{
                "caption": "添加表单",
                "href": "form&do=add",
                "icon": "pencil-square-o"
            }, {
                "-": "-"
            }, {
                "caption": "菜单管理",
                "href": "menu",
                "icon": "bars"
            }, {
                "caption": "添加菜单",
                "href": "menu&do=add",
                "icon": "edit"
            }]
        }, {
            "-": "-"
        }, {
            "caption": "检查更新",
            "href": "patch&do=check&force=1",
            "target": "iPHP_FRAME",
            "icon": "repeat"
        }, {
            "-": "-"
        }, {
            "caption": "官方网站",
            "href": "http://www.idreamsoft.com",
            "target": "_blank",
            "icon": "star"
        }, {
            "caption": "帮助文档",
            "href": "http://www.idreamsoft.com/help/",
            "target": "_blank",
            "icon": "question-circle"
        }


    ]
}]
